name: chem_gcn_cpu
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - black=23.11.0
  - blas=1.0=mkl
  - bottleneck
  - brotli
  - brotli-python
  - ca-certificates
  - certifi
  - cffi
  - click
  - colorama
  - contourpy
  - cpuonly
  - cryptography
  - cycler
  - filelock
  - fonttools
  - freetype
  - giflib
  - gmpy2
  - icu
  - idna
  - importlib_resources
  - intel-openmp
  - jinja2
  - joblib
  - jpeg
  - kiwisolver
  - krb5
  - lerc
  - libblas
  - libcblas
  - libclang
  - libdeflate
  - libjpeg-turbo
  - liblapack
  - libpng
  - libpq
  - libtiff
  - libuv
  - libwebp
  - libwebp-base
  - lz4-c
  - markupsafe
  - matplotlib
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mpmath
  - munkres
  - networkx
  - numexpr
  - numpy
  - openjpeg
  - openssl
  - packaging
  - pandas
  - pathspec
  - pillow
  - pip
  - platformdirs
  - pyopenssl
  - pyparsing
  - pytorch
  - pytorch-mutex
  - pytz
  - pyyaml
  - qt-main
  - requests
  - scikit-learn
  - scipy
  - setuptools
  - sip
  - six
  - sqlite
  - sympy
  - tbb
  - tk
  - tomli
  - torchaudio
  - torchvision
  - tornado
  - typing_extensions
  - urllib3
  - wheel
  - xz
  - zlib
  - zstd
  - pip:
    - rdkit==2023.9.2
